### ISSUE TITLE
Updated release?

### ISSUE THREAD

**Issue by romanovzky** [heal-research/pyoperon#16]
Hi,
The current version on `pypi` is lagging behind the builds here. Additionally, the builds in `Actions` only keep artefacts for a few months. Could it be possible to release a new version with the current code?
Cheers

**Comment by foolnotion** [comment]
Hi, yes, I believe this should be possible now (again). The reason we weren't able to release on `pypi` anymore was because with the switch to C++20 there was simply no `manylinux` compatible platform for us to use. Now I see that they have updated the compatible images so I will try again.

**Comment by foolnotion** [comment]
Hi, I made a test release on https://test.pypi.org/project/pyoperon/0.4.0/#files

Could you please check if it works for you?

**Comment by romanovzky** [comment]
Hi! I've tested the python 3.12 wheel and I was able to successfully run [this example](https://raw.githubusercontent.com/heal-research/pyoperon/main/example/operon-bindings.py).

By the way, I've released the code for my paper and I had to include the wheels form the action pages to guarantee reproducibility, you can check [here](https://gitlab.com/miguel.romao/symbolic-regression-bsm) how I've done it.

**Comment by foolnotion** [comment]
Cool, in the meanwhile I have figured it out how to build `manylinux_2_28` wheels using the official [docker images](https://github.com/pypa/manylinux?tab=readme-ov-file#docker-images) so I can release that version on PyPI as well (it'll take me a while due to busy times but hopefully real soon).

**Comment by foolnotion** [comment]
By the way, could you paste the link to the specific action you downloaded the wheels from? Thanks!

**Comment by romanovzky** [comment]
Hi,
Sure, I'm pretty sure it was this action https://github.com/heal-research/pyoperon/actions/runs/8570655759

I've updated our README to link to it.
