### ISSUE TITLE
installl the pyoperon by "pip install pyoperon"

### ISSUE THREAD

**Issue by luokuang2001** [heal-research/pyoperon#20]
I installled the pyoperon by "pip install pyoperon"
https://pypi.org/project/pyoperon/

Then I run the "operon-skilearn.py"
it thew out the error:

Traceback (most recent call last):
  File "/home/lk/pyoperon/example/operon-sklearn.py", line 62, in <module>
    reg.fit(X_train, y_train)
  File "/home/lk/pyoperon/pyoperon/sklearn.py", line 427, in fit
    ds                    = op.Dataset(D)
                            ^^^^^^^^^^
AttributeError: module 'pyoperon' has no attribute 'Dataset'

How can I fix it?
Thank you

**Comment by foolnotion** [comment]
Hi,

The version currently on PyPI is outdated. Could you try one of the wheels from our recent release? (following a testing period, the 0.4.0 release will also be uploaded to PyPI).

https://github.com/heal-research/pyoperon/releases/tag/v0.4.0

To install, select the appropriate wheel (same arch, same python version) and install it with `pip install`.

**Comment by luokuang2001** [comment]
Hello,
I install with :
"pip install pyoperon-0.4.0-cp312-cp312-manylinux_2_28_x86_64.whl" again, 
Processing ./pyoperon-0.4.0-cp312-cp312-manylinux_2_28_x86_64.whl
Installing collected packages: pyoperon
Successfully installed pyoperon-0.4.0
![Picture1](https://github.com/heal-research/pyoperon/assets/58783308/c0d8f8ea-ab55-4e71-a4b4-a7c4d8edfebd)


but when I run  the "operon-skilearn.py" again, it throws the error:
"
Traceback (most recent call last):
  File "/home/lk/pyoperon/example/operon-sklearn.py", line 11, in <module>
    from pyoperon.sklearn import SymbolicRegressor
  File "/home/lk/pyoperon/pyoperon/__init__.py", line 4, in <module>
    from .pyoperon import *
ModuleNotFoundError: No module named 'pyoperon.pyoperon'
"

How can I fix it?
Thank you

**Comment by luokuang2001** [comment]
Sorry,
I confused the instructions in https://github.com/heal-research/pyoperon?tab=readme-ov-file and the "pip install" way.
I have solved my problem, thank you a lot!
