### ISSUE TITLE
TypeError: cannot pickle 'pyoperon.pyoperon.Variable' object

### ISSUE THREAD

**Issue by dspanah** [heal-research/pyoperon#7]
I'm tryring to save a pyoperon model using pickle:

```
from pyoperon.sklearn import SymbolicRegressor
reg = SymbolicRegressor()
reg.fit(X_train, y_train)

filename = 'operon_model.sav'
pickle.Dump(reg, open(filename, 'wb'))
```
but I get the following error:
```
TypeError: cannot pickle 'pyoperon.pyoperon.Variable' object
```
Can help me with this issue?
Thanks

**Comment by foolnotion** [comment]
Hi, thanks for the bug report and sorry for the delayed reply. A fix for this issue will be included in the next release of `pyoperon`, which should happen within the week.
